#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install haproxy -y
sudo chown -R "$USER":"$USER" /etc/haproxy
echo -e "listen load_balancer\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 421842-web-01 52.207.73.79:80 check\n\tserver 421842-web-02 3.85.177.63:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
