#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install haproxy -y
sudo chown -R "$USER":"$USER" /etc/haproxy
front="frontend my_frontend\n\tbind *:80\n\tmode http\n\tdefault_backend my_backend"
back="backend my_backend\n\tmode http\n\tbalance roundrobin\n\tserver 421842-web-01 52.207.73.79 check\n\tserver 421842-web-02 3.85.177.63 check"
echo -e "$front" >> /etc/haproxy/haproxy.cfg
echo -e "$back" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
